<?php

namespace Designer\Studio\Services;

use Designer\Studio\Services\Storage\PageRepository;
use Designer\Studio\Services\Storage\ComponentRepository;
use Designer\Studio\DataTransferObjects\PageData;
use Illuminate\Support\Facades\File;

class BladeGenerator
{
    public function __construct(
        protected PageRepository $pages,
        protected ComponentRepository $components
    ) {}

    protected function getOutputPath(): string
    {
        return config('studio.output_path', resource_path('views/designer'));
    }

    /**
     * Generate Blade file for a single page
     */
    public function generatePage(string $pageSlug): string
    {
        $page = $this->pages->find($pageSlug);

        if (!$page) {
            throw new \RuntimeException("Page not found: {$pageSlug}");
        }

        $blade = $this->buildPageBlade($page);
        $outputPath = $this->getOutputPath() . "/{$page->slug}.blade.php";

        // Ensure directory exists
        $directory = dirname($outputPath);
        if (!File::isDirectory($directory)) {
            File::makeDirectory($directory, 0755, true);
        }

        File::put($outputPath, $blade);

        return $outputPath;
    }

    /**
     * Generate Blade files for all pages
     */
    public function generateAll(): array
    {
        $generated = [];

        foreach ($this->pages->all() as $page) {
            $generated[] = $this->generatePage($page->slug);
        }

        return $generated;
    }

    /**
     * Build the Blade content for a page
     */
    protected function buildPageBlade(PageData $page): string
    {
        $layout = $page->layout ?: config('studio.default_layout', 'layouts.app');

        $sections = [];
        $sections[] = "@extends('{$layout}')";
        $sections[] = "";

        // Add SEO meta if available
        if (!empty($page->meta['seo_title'])) {
            $sections[] = "@section('title', " . var_export($page->meta['seo_title'], true) . ")";
        }

        $sections[] = "@section('content')";

        // Sort components by order and render each
        $sortedComponents = collect($page->components)->sortBy('order');

        foreach ($sortedComponents as $instance) {
            $component = $this->components->find($instance['component_ref']);

            if (!$component) {
                $sections[] = "    {{-- Component not found: {$instance['component_ref']} --}}";
                continue;
            }

            $sections[] = "";
            $sections[] = "    {{-- {$component->title} --}}";

            // Render the component HTML with variables
            $rendered = $this->renderComponentWithVariables(
                $component->html,
                $instance['variables'] ?? []
            );

            // Indent the rendered HTML
            $indented = collect(explode("\n", $rendered))
                ->map(fn($line) => "    " . $line)
                ->implode("\n");

            $sections[] = $indented;
        }

        $sections[] = "";
        $sections[] = "@endsection";

        // Add header comment
        $header = [
            "{{--",
            "    Generated by Designer Studio",
            "    Page: {$page->title}",
            "    Generated at: " . now()->toIso8601String(),
            "    ",
            "    WARNING: Manual edits will be overwritten when regenerated.",
            "--}}",
            "",
        ];

        return implode("\n", array_merge($header, $sections));
    }

    /**
     * Render component HTML, converting {{ $var ?? 'default' }} to static values
     */
    protected function renderComponentWithVariables(string $html, array $variables): string
    {
        // Replace Blade variable syntax with actual values
        // Pattern: {{ $varName ?? 'default' }} or {{ $varName ?? "default" }}
        $pattern = '/{{\s*\$(\w+)\s*\?\?\s*[\'"]([^\'"]*)[\'"]?\s*}}/';

        return preg_replace_callback($pattern, function ($matches) use ($variables) {
            $varName = $matches[1];
            $default = $matches[2];

            $value = $variables[$varName] ?? $default;

            // Escape for HTML output
            return e($value);
        }, $html);
    }

    /**
     * Generate component partials (optional, for reusable includes)
     */
    public function generateComponentPartials(): array
    {
        $generated = [];
        $partialsPath = $this->getOutputPath() . '/partials';

        if (!File::isDirectory($partialsPath)) {
            File::makeDirectory($partialsPath, 0755, true);
        }

        foreach ($this->components->all() as $component) {
            $filename = "_{$component->name}.blade.php";
            $filepath = "{$partialsPath}/{$filename}";

            $content = $this->buildComponentPartial($component);
            File::put($filepath, $content);

            $generated[] = $filepath;
        }

        return $generated;
    }

    protected function buildComponentPartial($component): string
    {
        $header = [
            "{{--",
            "    Component: {$component->title}",
            "    Usage: @include('designer.partials._{$component->name}', ['var' => 'value'])",
            "--}}",
            "",
        ];

        return implode("\n", $header) . $component->html;
    }

    /**
     * Remove all generated Blade files (for clean uninstall)
     */
    public function purge(): bool
    {
        $outputPath = $this->getOutputPath();

        if (File::isDirectory($outputPath)) {
            return File::deleteDirectory($outputPath);
        }

        return true;
    }
}
